name: Auto publish
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v6

      - name: Install development dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Fetch latest release
        run: |
          RELEASE=$(curl --silent "https://api.github.com/repos/vale-cli/vale/releases/latest" | jq -r .tag_name)
          RELEASE=${RELEASE#v} # Remove 'v' prefix
          echo "Latest release is $RELEASE"
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV

      - name: Get npm project version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "NPM project version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Compare versions and update if needed
        run: |
          if [ "${{ env.RELEASE }}" != "${{ env.VERSION }}" ]; then
              echo "Versions do not match. Latest release is ${{ env.RELEASE }} but npm project version is $VERSION"
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              pnpm version ${{ env.RELEASE }}
              # pnpm version creates a commit, so we need to push it
              git push
              pnpm publish --access=public
            else
              echo "Versions match"
            fi
